// Closed, versioned effect ontology (spec ch. 9). Extend by bumping TAXONOMY_VERSION.
export const TAXONOMY_VERSION = '1.0.0';

export const EFFECT_TYPES = {
  'text-reveal-lines': 'Text revealed line by line, usually each line translated from below inside an overflow:hidden mask.',
  'text-reveal-words': 'Text revealed word by word (split into words, staggered).',
  'text-reveal-chars': 'Text revealed character by character (split into chars, staggered).',
  'text-scramble': 'Characters cycle through random glyphs before settling.',
  'fade-up-reveal': 'Element fades in while translating up when it enters the viewport.',
  'scale-reveal': 'Element scales from a smaller/larger size to its natural size when revealed.',
  marquee: 'Content scrolls horizontally in an infinite linear loop.',
  'image-reveal-clip': 'Media revealed by animating clip-path / an overflow mask.',
  'image-parallax': 'Media translated at a different speed than the scroll (scrubbed).',
  'image-distortion-hover': 'WebGL shader distorts an image on hover / mouse move.',
  'image-trail': 'Images spawn and follow the mouse trail.',
  'gallery-drag': 'Draggable gallery / slider with inertia.',
  'horizontal-scroll-section': 'Vertical scroll drives a horizontal translation of a pinned track.',
  'pinned-sequence': 'Section pinned while scroll scrubs an animation sequence.',
  'scroll-scrubbed-video': 'Video currentTime driven by scroll.',
  'image-sequence-canvas': 'Frame sequence drawn to a canvas, driven by scroll.',
  counter: 'Numbers count up.',
  'magnetic-element': 'Element is attracted toward the pointer when hovered.',
  'custom-cursor': 'Custom DOM cursor following the pointer with lag.',
  'cursor-follower-media': 'Media preview follows the cursor over list items.',
  'tilt-3d': '3D tilt following the pointer.',
  'mouse-parallax': 'Layers translate proportionally to pointer position.',
  'page-transition': 'Animated transition between routes.',
  preloader: 'Loading screen / intro sequence before content is shown.',
  'menu-overlay': 'Full-screen menu overlay animation.',
  'fluid-background-shader': 'Full-bleed WebGL background driven by time/pointer.',
  'noise-gradient': 'Animated noise / gradient shader.',
  particles: 'Particle system (WebGL points or canvas2d).',
  'gpgpu-simulation': 'GPU simulation (ping-pong render targets, e.g. GPUComputationRenderer) feeding a visual effect.',
  '3d-scene': 'Three.js / WebGL 3D scene with meshes, lights, camera.',
  'camera-scroll-path': '3D camera travelling along a path driven by the scroll (position / rotation / fov keyframes).',
  '3d-object-motion': '3D object moved, rotated or scaled over time, on load, on scroll or in a loop.',
  'press-hold': 'Effect triggered by pressing and holding (pointer down), released on pointer up.',
  'tabs': 'Tabs / segmented control switching panels with a transition.',
  'click-feedback': 'Visual feedback on click that does not navigate (ripple, bounce, colour flash, state change).',
  'scene-color-shift': 'The whole décor changes colour / tone while scrolling (background and text swap, dark ↔ light).',
  'zoom-through': 'An element grows until it fills the viewport (zoom into an object / a word) and the next scene starts inside it.',
  'media-choreography': 'Several images animated as one composition: spiral, orbit / circle, stack, fan, collage — moving together on scroll, time or pointer.',
  'scroll-rotation': 'Element (or group) rotating with the scroll.',
  'media-expand': 'A media frame expands (width, clip-path, inset) from a card to full screen while scrolling.',
  'model-viewer': '3D model presented in a viewer.',
  'split-screen': 'Split layout where halves move independently.',
  'sticky-stack-cards': 'Cards stack on top of each other using sticky positioning / pinning.',
  accordion: 'Expand / collapse panels.',
  'blend-mode-text': 'Text using mix-blend-mode (difference, exclusion...).',
  'svg-path-draw': 'SVG stroke drawn progressively (stroke-dashoffset / DrawSVG).',
  'morph-svg': 'SVG path morphing.',
  lottie: 'Lottie animation.',
  'grain-overlay': 'Animated film grain overlay.',
  'hover-state': 'Styled hover state (color / scale / underline / background transition).',
  'smooth-scroll': 'Global smooth scrolling system.',
  other: 'Motion that does not match a known type.',
};

export const TRIGGERS = ['load', 'scroll-enter', 'scroll-scrub', 'hover', 'press', 'mouse-move', 'click', 'drag', 'time-loop', 'route-change'];
export const TECHNIQUES = ['css-transition', 'css-keyframes', 'css-scroll-timeline', 'waapi', 'gsap-tween', 'gsap-timeline', 'gsap-scrolltrigger', 'framer-motion', 'webgl-shader', 'three-scene', 'canvas2d', 'svg', 'lottie', 'video', 'js-inline-style'];

export function isKnownType(t) {
  return Object.prototype.hasOwnProperty.call(EFFECT_TYPES, t);
}

// Usual names (for people and for web searches) of each effect type, used by focus analyses and the dashboard.
export const COMMON_NAMES = {
  'text-reveal-lines': { en: 'Masked line reveal', fr: 'Révélation de texte ligne par ligne', aka: ['split text line reveal', 'text mask reveal', 'staggered lines'], search: 'gsap splittext masked line reveal' },
  'text-reveal-words': { en: 'Staggered word reveal', fr: 'Révélation mot par mot', aka: ['word stagger', 'split words animation'], search: 'gsap split words stagger reveal' },
  'text-reveal-chars': { en: 'Character stagger reveal', fr: 'Révélation lettre par lettre', aka: ['char animation', 'letter stagger'], search: 'gsap splittext chars stagger' },
  'text-scramble': { en: 'Text scramble / decode', fr: 'Texte brouillé qui se décode', aka: ['scramble text', 'glitch text decode'], search: 'text scramble effect javascript' },
  'fade-up-reveal': { en: 'Fade-up on scroll', fr: 'Apparition en fondu vers le haut', aka: ['reveal on scroll', 'fade in up'], search: 'fade up reveal on scroll gsap' },
  'scale-reveal': { en: 'Scale reveal', fr: 'Apparition par mise à l’échelle', aka: ['zoom in reveal'], search: 'scale in reveal animation scroll' },
  marquee: { en: 'Infinite marquee', fr: 'Bandeau défilant infini', aka: ['ticker', 'infinite scroll text', 'logo marquee'], search: 'infinite marquee gsap seamless' },
  'image-reveal-clip': { en: 'Clip-path image reveal', fr: 'Révélation d’image par masque', aka: ['curtain reveal', 'mask reveal', 'inset reveal'], search: 'clip-path image reveal animation' },
  'image-parallax': { en: 'Image parallax', fr: 'Parallaxe d’image', aka: ['scroll parallax', 'inner parallax'], search: 'image parallax scrolltrigger' },
  'image-distortion-hover': { en: 'WebGL hover distortion', fr: 'Distorsion d’image au survol (WebGL)', aka: ['displacement hover', 'liquid hover', 'RGB shift hover'], search: 'webgl image hover distortion displacement codrops' },
  'image-trail': { en: 'Mouse image trail', fr: 'Traînée d’images au curseur', aka: ['cursor image trail'], search: 'image trail mouse effect codrops' },
  'gallery-drag': { en: 'Draggable slider with inertia', fr: 'Galerie à glisser avec inertie', aka: ['drag carousel', 'momentum slider'], search: 'draggable slider inertia gsap' },
  'horizontal-scroll-section': { en: 'Horizontal scroll section', fr: 'Section à défilement horizontal', aka: ['pinned horizontal scroll'], search: 'horizontal scroll section scrolltrigger pin' },
  'pinned-sequence': { en: 'Pinned scroll sequence', fr: 'Séquence épinglée au scroll', aka: ['scrollytelling', 'sticky scroll animation'], search: 'scrolltrigger pin scrub sequence' },
  'scroll-scrubbed-video': { en: 'Scroll-scrubbed video', fr: 'Vidéo pilotée par le scroll', aka: ['video scrub'], search: 'scroll controlled video scrub' },
  'image-sequence-canvas': { en: 'Canvas image sequence', fr: 'Séquence d’images sur canvas', aka: ['apple style image sequence'], search: 'canvas image sequence scroll apple' },
  counter: { en: 'Number counter', fr: 'Compteur animé', aka: ['count up'], search: 'animated number counter gsap' },
  'magnetic-element': { en: 'Magnetic button', fr: 'Bouton magnétique', aka: ['magnetic hover'], search: 'magnetic button hover effect' },
  'custom-cursor': { en: 'Custom cursor', fr: 'Curseur personnalisé', aka: ['cursor follower', 'blend cursor'], search: 'custom cursor follower lerp' },
  'cursor-follower-media': { en: 'Hover image follower', fr: 'Image qui suit le curseur', aka: ['hover reveal list', 'list image preview'], search: 'hover image follow cursor list' },
  'tilt-3d': { en: '3D tilt on hover', fr: 'Inclinaison 3D au survol', aka: ['parallax tilt card'], search: '3d tilt card hover' },
  'mouse-parallax': { en: 'Mouse parallax', fr: 'Parallaxe à la souris', aka: ['pointer parallax'], search: 'mouse move parallax layers' },
  'page-transition': { en: 'Page transition', fr: 'Transition de page', aka: ['route transition', 'barba transition'], search: 'page transition barba swup gsap' },
  preloader: { en: 'Preloader intro', fr: 'Écran de chargement animé', aka: ['loading screen', 'intro animation'], search: 'website preloader animation gsap' },
  'menu-overlay': { en: 'Fullscreen menu overlay', fr: 'Menu plein écran animé', aka: ['overlay navigation'], search: 'fullscreen menu animation gsap' },
  'fluid-background-shader': { en: 'Fluid shader background', fr: 'Fond fluide (shader)', aka: ['gradient mesh', 'fluid simulation background'], search: 'webgl fluid background shader' },
  'noise-gradient': { en: 'Animated noise gradient', fr: 'Dégradé animé au bruit', aka: ['mesh gradient', 'grainy gradient'], search: 'animated noise gradient shader' },
  particles: { en: 'Particle system', fr: 'Système de particules', aka: ['points cloud'], search: 'three.js particles animation' },
  'gpgpu-simulation': { en: 'GPGPU particles', fr: 'Particules simulées sur GPU', aka: ['FBO particles', 'curl noise particles'], search: 'three.js gpgpu particles fbo' },
  '3d-scene': { en: '3D scene', fr: 'Scène 3D', aka: ['webgl scene'], search: 'three.js scene website' },
  'camera-scroll-path': { en: 'Scroll-driven 3D camera', fr: 'Caméra 3D pilotée par le scroll', aka: ['camera fly-through'], search: 'three.js camera scroll animation scrolltrigger' },
  '3d-object-motion': { en: 'Animated 3D object', fr: 'Objet 3D animé', aka: [], search: 'three.js object animation gsap' },
  'press-hold': { en: 'Press and hold interaction', fr: 'Interaction à appui long', aka: ['hold to reveal', 'long press progress'], search: 'press and hold button animation' },
  tabs: { en: 'Animated tabs', fr: 'Onglets animés', aka: ['segmented control'], search: 'animated tabs indicator' },
  'click-feedback': { en: 'Click feedback', fr: 'Retour visuel au clic', aka: ['ripple', 'button bounce'], search: 'button click feedback animation' },
  'scene-color-shift': { en: 'Background colour change on scroll', fr: 'Changement de décor au scroll', aka: ['theme switch on scroll', 'section color transition'], search: 'change background color on scroll scrolltrigger' },
  'zoom-through': { en: 'Zoom-through transition', fr: 'Zoom à travers', aka: ['scroll zoom into text', 'mask zoom'], search: 'zoom through text scroll animation' },
  'media-expand': { en: 'Expanding media on scroll', fr: 'Média qui s’agrandit au scroll', aka: ['image expand to fullscreen', 'scale up video on scroll'], search: 'image expand fullscreen on scroll gsap' },
  'media-choreography': { en: 'Image composition in motion', fr: 'Composition d’images animée', aka: ['gallery choreography'], search: 'creative image gallery animation gsap' },
  'scroll-rotation': { en: 'Rotate on scroll', fr: 'Rotation au scroll', aka: ['scroll-linked rotation', 'spinning on scroll'], search: 'rotate element on scroll scrolltrigger' },
  'sticky-stack-cards': { en: 'Stacking cards', fr: 'Cartes qui s’empilent', aka: ['sticky cards'], search: 'stacking cards scroll sticky' },
  accordion: { en: 'Accordion', fr: 'Accordéon', aka: [], search: 'accordion animation height' },
  'blend-mode-text': { en: 'Blend-mode text', fr: 'Texte en mode de fusion', aka: ['difference text'], search: 'mix-blend-mode difference text' },
  'svg-path-draw': { en: 'SVG line drawing', fr: 'Tracé SVG animé', aka: ['stroke draw', 'drawSVG'], search: 'svg path draw animation stroke-dashoffset' },
  'morph-svg': { en: 'SVG morph', fr: 'Morphing SVG', aka: [], search: 'svg morph animation' },
  lottie: { en: 'Lottie animation', fr: 'Animation Lottie', aka: ['bodymovin'], search: 'lottie web animation' },
  'grain-overlay': { en: 'Film grain overlay', fr: 'Grain animé', aka: ['noise overlay'], search: 'animated grain overlay css' },
  'hover-state': { en: 'Hover state', fr: 'État de survol', aka: ['hover effect'], search: 'hover effect css' },
  'smooth-scroll': { en: 'Smooth scroll', fr: 'Scroll fluide', aka: ['lenis'], search: 'lenis smooth scroll' },
  other: { en: 'Custom animation', fr: 'Animation sur mesure', aka: [], search: 'web animation' },
};
